#!/bin/bash

source $HOME/.config/recall/config

if [ "$STORAGELOCATION" == "" ]; then 
	exit 1;
fi 

SUCHE=$(zenity --entry --text="RECALL Suchbegriff" --entry-text="" --title="Suchbegriff")

TREFFER=$(grep -l -i "$SUCHE" $STORAGELOCATION/*txt| sed -e "s/\.txt$//g")

eog -n -w -s $TREFFER
