#!/bin/bash

CONFIG=$HOME/.config/recall/config

if [ ! -e $CONFIG ]; then 

	echo "# needs to be an absolute path" > $CONFIG
	echo "STORAGELOCATION=$HOME/Bilder/recall" >> $CONFIG
	echo "# size in byte" >> $CONFIG
	echo "CACHEMAXSIZE=1073741824" >> $CONFIG
	echo "# autodelete time in days" >> $CONFIG
	echo "AUTODELETETIMEFRAME=180" >> $CONFIG

fi

source $CONFIG

if [ "$STORAGELOCATION" == "" ]; then 
	exit 1;
fi 

if [ ! -e $STORAGELOCATION ]; then
	mkdir -p $STORAGELOCATION
fi

SIZE=$(du -s $STORAGELOCATION/|awk '{print $1;}')

if [ $SIZE -gt $CACHEMAXSIZE ]; then 
	DNAME=$(ls -d $STORAGELOCATION/*png 2>&1 | head -n 1 )
	if [[ "$DNAME" =~ ^/ ]]; then 
		rm -f $DNAME
	fi
fi 

find $STORAGELOCATION -iname "*txt" -ctime +$AUTODELETETIMEFRAME -delete

WLISTE=$(wmctrl -l | grep -c -E -f  $HOME/.config/recall/exclude )

if [ $WLISTE -eq 0 ]; then

	FNAME=$(date +"%F_%H-%M-%S.jpg")
	FILENAME=$STORAGELOCATION/$FNAME
	flameshot full -r | convert - -quality 30 $FILENAME
	tesseract $FILENAME $FILENAME
	
fi
