#!/bin/bash

CONFIG=$HOME/.config/recall/config

if [ ! -e $CONFIG ]; then 

	echo "# needs to be an absolute path" > $CONFIG
	echo "STORAGELOCATION=$HOME/Bilder/recall" >> $CONFIG
	echo "# size in byte" >> $CONFIG
	echo "CACHEMAXSIZE=1073741824" >> $CONFIG
	echo "# autodelete time in days" >> $CONFIG
	echo "AUTODELETETIMEFRAME=180" >> $CONFIG

fi

source $CONFIG


if [ "$STORAGELOCATION" == "" ]; then 
	exit 1;
fi 

if [ -e $STORAGELOCATION ]; then
	rm -f $STORAGELOCATION/*
fi



